# Generated by Django 5.2.16 on 2026-08-10 12:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('headline', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('looking_for', models.JSONField(blank=True, default=list)),
                ('availability', models.CharField(choices=[('unavailable', 'Unavailable'), ('open_to_projects', 'Open to projects'), ('open_to_work', 'Open to work'), ('open_to_both', 'Open to projects and work')], default='unavailable', max_length=30)),
                ('location_label', models.CharField(blank=True, max_length=120)),
                ('website_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('show_projects', models.BooleanField(default=True)),
                ('show_activity', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='developer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['is_public', 'updated_at'], name='profile_public_updated_idx'), models.Index(fields=['availability', 'updated_at'], name='profile_availability_idx')],
            },
        ),
    ]
