# Generated by Django 5.2.16 on 2026-08-08 23:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0003_remove_workspaceinvitation_invitation_max_uses_gte_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('workspace.member_joined', 'Workspace member joined'), ('task.assigned', 'Task assigned'), ('task.updated', 'Task updated'), ('task.completed', 'Task completed'), ('calendar.invited', 'Calendar invited'), ('calendar.updated', 'Calendar updated'), ('chat.message_reply', 'Message reply'), ('file.uploaded', 'File uploaded'), ('github.repository_linked', 'GitHub repository linked'), ('system', 'System')], max_length=80)),
                ('category', models.CharField(choices=[('workspace', 'Workspace'), ('chat', 'Chat'), ('task', 'Task'), ('calendar', 'Calendar'), ('file', 'File'), ('github', 'GitHub'), ('system', 'System')], max_length=30)),
                ('title', models.CharField(max_length=160)),
                ('body', models.CharField(blank=True, max_length=500)),
                ('object_type', models.CharField(blank=True, max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('deduplication_key', models.CharField(blank=True, max_length=191, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['recipient', 'created_at'], name='notify_recipient_time_idx'), models.Index(fields=['recipient', 'read_at'], name='notify_recipient_read_idx'), models.Index(fields=['workspace', 'created_at'], name='notify_workspace_time_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deduplication_key__isnull', False)), fields=('recipient', 'deduplication_key'), name='notify_recipient_dedup_unique')],
            },
        ),
    ]
