# Generated by Django 5.2.16 on 2026-08-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_account_status_user_auth_providers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
