# Generated by Django 5.2.16 on 2026-08-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_deletion_requested_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legaldocumentacceptance',
            options={'ordering': ('-accepted_at',)},
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_previous_status',
            field=models.CharField(blank=True, choices=[('provisional', 'Provisional'), ('verification_required', 'Verification required'), ('active', 'Active'), ('restricted', 'Restricted'), ('suspended', 'Suspended'), ('deletion_pending', 'Deletion pending')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('provisional', 'Provisional'), ('verification_required', 'Verification required'), ('active', 'Active'), ('restricted', 'Restricted'), ('suspended', 'Suspended'), ('deletion_pending', 'Deletion pending')], default='active', max_length=30),
        ),
    ]
