# Generated by Django 5.2.16 on 2026-08-08 21:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0003_remove_workspaceinvitation_invitation_max_uses_gte_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('workspace', 'Workspace'), ('chat', 'Chat'), ('task', 'Task'), ('calendar', 'Calendar'), ('file', 'File'), ('map', 'Map'), ('github', 'GitHub'), ('account', 'Account'), ('system', 'System')], max_length=30)),
                ('event_type', models.CharField(choices=[('workspace.created', 'Workspace created'), ('workspace.member_joined', 'Workspace member joined'), ('chat.channel_created', 'Channel created'), ('chat.message_sent', 'Message sent'), ('task.created', 'Task created'), ('task.updated', 'Task updated'), ('task.completed', 'Task completed'), ('calendar.created', 'Calendar event created'), ('calendar.updated', 'Calendar event updated'), ('file.uploaded', 'File uploaded'), ('map.place_created', 'Place created'), ('github.repository_linked', 'GitHub repository linked'), ('github.synced', 'GitHub repository synced')], max_length=80)),
                ('visibility', models.CharField(choices=[('all_members', 'All members'), ('contributors', 'Contributors'), ('managers', 'Managers')], default='all_members', max_length=30)),
                ('source', models.CharField(choices=[('internal', 'Internal'), ('github', 'GitHub'), ('system', 'System')], default='internal', max_length=30)),
                ('object_type', models.CharField(blank=True, max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=128)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('deduplication_key', models.CharField(blank=True, max_length=191, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activity_events', to=settings.AUTH_USER_MODEL)),
                ('subject_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_activity_events', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('-occurred_at', '-created_at'),
                'indexes': [models.Index(fields=['workspace', 'occurred_at'], name='activity_workspace_time_idx'), models.Index(fields=['actor', 'occurred_at'], name='activity_actor_time_idx'), models.Index(fields=['event_type', 'occurred_at'], name='activity_type_time_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deduplication_key__isnull', False)), fields=('deduplication_key',), name='activity_unique_dedup_key')],
            },
        ),
    ]
