# Generated by Django 5.2.16 on 2026-08-08 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_deleted_by'),
        ('workspaces', '0003_remove_workspaceinvitation_invitation_max_uses_gte_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='channel',
            name='unique_active_channel_name',
        ),
        migrations.RemoveIndex(
            model_name='channel',
            name='channel_ws_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='channel',
            name='channel_ws_position_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_msg_channel_idx',
            old_name='message_channel_created_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_msg_author_idx',
            old_name='message_author_created_idx',
        ),
        migrations.AddField(
            model_name='channel',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['workspace', 'is_archived', 'position'], name='chat_channel_ws_arch_idx'),
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('workspace', 'name'), name='unique_active_channel_name_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 0)), name='channel_position_gte_0'),
        ),
    ]
