# Generated by Django 5.2.16 on 2026-08-08 20:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0003_remove_workspaceinvitation_invitation_max_uses_gte_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('github_user_id', models.PositiveBigIntegerField(unique=True)),
                ('login', models.CharField(max_length=100)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('access_token_encrypted', models.TextField(editable=False)),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_token_encrypted', models.TextField(blank=True, editable=False)),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('token_type', models.CharField(default='bearer', max_length=50)),
                ('scope', models.CharField(blank=True, max_length=500)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('login',),
            },
        ),
        migrations.CreateModel(
            name='GitHubOAuthState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_oauth_states', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_oauth_states', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at', 'used_at'], name='ghstate_exp_used_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceGitHubRepository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installation_id', models.PositiveBigIntegerField()),
                ('github_repository_id', models.PositiveBigIntegerField()),
                ('owner_login', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('html_url', models.URLField(max_length=500)),
                ('default_branch', models.CharField(blank=True, max_length=255)),
                ('is_private', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('stargazers_count', models.PositiveIntegerField(default=0)),
                ('forks_count', models.PositiveIntegerField(default=0)),
                ('open_issues_count', models.PositiveIntegerField(default=0)),
                ('pushed_at', models.DateTimeField(blank=True, null=True)),
                ('unlinked_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_github_repositories', to=settings.AUTH_USER_MODEL)),
                ('unlinked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlinked_github_repositories', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_repositories', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('-is_primary', 'full_name'),
                'indexes': [models.Index(fields=['workspace', 'unlinked_at'], name='ghrepo_ws_active_idx'), models.Index(fields=['installation_id'], name='ghrepo_install_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('unlinked_at__isnull', True)), fields=('workspace', 'github_repository_id'), name='unique_active_workspace_repo'), models.UniqueConstraint(condition=models.Q(('is_primary', True), ('unlinked_at__isnull', True)), fields=('workspace',), name='unique_primary_workspace_repo')],
            },
        ),
    ]
