# Generated by Django 5.2.16 on 2026-08-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githuboauthstate',
            name='installation_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
