# Generated by Django 5.2.16 on 2026-08-08 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_workspaceinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workspaceinvitation',
            name='invitation_max_uses_gte_1',
        ),
        migrations.RenameIndex(
            model_name='workspaceinvitation',
            new_name='ws_invite_active_idx',
            old_name='workspace_invite_active_idx',
        ),
        migrations.RenameIndex(
            model_name='workspaceinvitation',
            new_name='ws_invite_expiry_idx',
            old_name='workspace_invite_expiry_idx',
        ),
        migrations.RenameIndex(
            model_name='workspacemember',
            new_name='ws_member_role_idx',
            old_name='workspace_role_idx',
        ),
        migrations.RenameIndex(
            model_name='workspacemember',
            new_name='ws_user_active_idx',
            old_name='user_active_membership_idx',
        ),
        migrations.AddField(
            model_name='workspaceinvitation',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspaceinvitation',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_workspace_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspaceinvitation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='workspaceinvitation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workspace_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='workspaceinvitation',
            constraint=models.CheckConstraint(condition=models.Q(('max_uses__gte', 1)), name='workspace_invite_max_uses_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='workspaceinvitation',
            constraint=models.CheckConstraint(condition=models.Q(('use_count__lte', models.F('max_uses'))), name='workspace_invite_use_count_lte_max'),
        ),
    ]
