# Generated by Django 5.2.16 on 2026-08-08 18:11

import django.db.models.deletion
import uuid
import workspace_files.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0003_remove_workspaceinvitation_invitation_max_uses_gte_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workspace_folders', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_workspace_folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workspace_files.workspacefolder')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WorkspaceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, upload_to=workspace_files.models.workspace_file_upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(max_length=64)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_workspace_files', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_workspace_files', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_files', to='workspaces.workspace')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='workspace_files.workspacefolder')),
            ],
            options={
                'ordering': ('display_name', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='workspacefolder',
            index=models.Index(fields=['workspace', 'parent'], name='wsfolder_ws_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacefolder',
            index=models.Index(fields=['workspace', 'deleted_at'], name='wsfolder_deleted_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspacefolder',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('parent__isnull', True)), fields=('workspace', 'name'), name='unique_active_root_folder'),
        ),
        migrations.AddConstraint(
            model_name='workspacefolder',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('parent__isnull', False)), fields=('workspace', 'parent', 'name'), name='unique_active_child_folder'),
        ),
        migrations.AddIndex(
            model_name='workspacefile',
            index=models.Index(fields=['workspace', 'folder'], name='wsfile_ws_folder_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacefile',
            index=models.Index(fields=['workspace', 'deleted_at'], name='wsfile_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacefile',
            index=models.Index(fields=['sha256'], name='wsfile_sha256_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspacefile',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('folder__isnull', True)), fields=('workspace', 'display_name'), name='unique_active_root_file'),
        ),
        migrations.AddConstraint(
            model_name='workspacefile',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('folder__isnull', False)), fields=('workspace', 'folder', 'display_name'), name='unique_active_folder_file'),
        ),
    ]
