# Generated by Django 5.2.16 on 2026-08-08 18:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0003_remove_workspaceinvitation_invitation_max_uses_gte_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('timezone', models.CharField(default='Asia/Tokyo', max_length=64)),
                ('is_all_day', models.BooleanField(default=False)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('recurrence_frequency', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=20)),
                ('recurrence_interval', models.PositiveSmallIntegerField(default=1)),
                ('recurrence_weekdays', models.JSONField(blank=True, default=list)),
                ('recurrence_until', models.DateField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calendar_events', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_calendar_events', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='CalendarEventParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('tentative', 'Tentative'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_calendar_participants', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participants', to='scheduling.calendarevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='calendar_events', through='scheduling.CalendarEventParticipant', through_fields=('event', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='calendareventparticipant',
            index=models.Index(fields=['user', 'response'], name='calendar_participant_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendareventparticipant',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_calendar_event_participant'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['workspace', 'deleted_at'], name='calendar_ws_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['starts_at'], name='calendar_starts_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['start_date'], name='calendar_start_date_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['recurrence_until'], name='calendar_repeat_until_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarevent',
            constraint=models.CheckConstraint(condition=models.Q(('recurrence_interval__gte', 1)), name='calendar_repeat_interval_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='calendarevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_date__isnull', False), ('ends_at__isnull', True), ('is_all_day', True), ('start_date__isnull', False), ('starts_at__isnull', True)), models.Q(('end_date__isnull', True), ('ends_at__isnull', False), ('is_all_day', False), ('start_date__isnull', True), ('starts_at__isnull', False)), _connector='OR'), name='calendar_event_schedule_shape'),
        ),
        migrations.AddConstraint(
            model_name='calendarevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_date__gte', models.F('start_date')), ('is_all_day', True)), models.Q(('ends_at__gt', models.F('starts_at')), ('is_all_day', False)), _connector='OR'), name='calendar_event_valid_period'),
        ),
    ]
