# Generated by Django 5.2.16 on 2026-07-25 19:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0002_workspaceinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(allow_unicode=True, max_length=80)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('channel_type', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice')], default='text', max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_channels', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('position', 'created_at'),
                'indexes': [models.Index(fields=['workspace', 'channel_type', 'is_archived'], name='channel_ws_status_idx'), models.Index(fields=['workspace', 'position'], name='channel_ws_position_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('workspace', 'name'), name='unique_active_channel_name')],
            },
        ),
    ]
