# Generated by Django 5.2.16 on 2026-08-10 12:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0003_remove_workspaceinvitation_invitation_max_uses_gte_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExploreProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('summary', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('idea', 'Idea'), ('building', 'Building'), ('active', 'Active'), ('maintenance', 'Maintenance'), ('completed', 'Completed')], default='building', max_length=30)),
                ('recruitment_status', models.CharField(choices=[('closed', 'Closed'), ('open', 'Open')], default='closed', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('wanted_roles', models.JSONField(blank=True, default=list)),
                ('repository_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('cover_image_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explore_projects', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='explore_project', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('-published_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('discussion', 'Discussion'), ('project_recruitment', 'Project recruitment'), ('showcase', 'Showcase'), ('question', 'Question')], default='discussion', max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_posts', to='explore.exploreproject')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ExploreDeveloperProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('headline', models.CharField(blank=True, max_length=120)),
                ('bio', models.CharField(blank=True, max_length=500)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('availability', models.CharField(blank=True, max_length=120)),
                ('portfolio_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('is_discoverable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='explore_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['is_discoverable', 'updated_at'], name='explore_people_disc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExploreEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('location_name', models.CharField(blank=True, max_length=160)),
                ('online_url', models.URLField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explore_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('starts_at', 'created_at'),
                'indexes': [models.Index(fields=['is_published', 'starts_at'], name='explore_event_pub_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='exploreproject',
            index=models.Index(fields=['is_published', 'published_at'], name='explore_project_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='exploreproject',
            index=models.Index(fields=['recruitment_status', 'published_at'], name='explore_project_recruit_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['is_published', 'created_at'], name='community_post_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['kind', 'created_at'], name='community_post_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='communitypost',
            constraint=models.CheckConstraint(condition=models.Q(('is_published', False), ('deleted_at__isnull', True), _connector='OR'), name='community_published_not_deleted'),
        ),
    ]
