# Generated by Django 5.2.16 on 2026-08-10 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExploreDeveloperProfile',
        ),
    ]
