# Generated by Django 5.2.16 on 2026-08-08 18:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0003_remove_workspaceinvitation_invitation_max_uses_gte_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspacePlace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workspace_places', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_workspace_places', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('name', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='WorkspaceLocationShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_location_shares', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_shares', to='workspaces.workspace')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_shares', to='locations.workspaceplace')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.AddIndex(
            model_name='workspaceplace',
            index=models.Index(fields=['workspace', 'deleted_at'], name='place_ws_deleted_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspaceplace',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='place_latitude_valid'),
        ),
        migrations.AddConstraint(
            model_name='workspaceplace',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='place_longitude_valid'),
        ),
        migrations.AddIndex(
            model_name='workspacelocationshare',
            index=models.Index(fields=['workspace', 'expires_at'], name='locshare_ws_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacelocationshare',
            index=models.Index(fields=['user', 'ended_at'], name='locshare_user_end_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspacelocationshare',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='locshare_latitude_valid'),
        ),
        migrations.AddConstraint(
            model_name='workspacelocationshare',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='locshare_longitude_valid'),
        ),
        migrations.AddConstraint(
            model_name='workspacelocationshare',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('workspace', 'user'), name='unique_open_location_share'),
        ),
    ]
